// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateVolumeSnapshotReader is a Reader for the CreateVolumeSnapshot structure.
type CreateVolumeSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVolumeSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVolumeSnapshotOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/volumes/{volume_id}/snapshots] createVolumeSnapshot", response, response.Code())
	}
}

// NewCreateVolumeSnapshotOK creates a CreateVolumeSnapshotOK with default headers values
func NewCreateVolumeSnapshotOK() *CreateVolumeSnapshotOK {
	return &CreateVolumeSnapshotOK{}
}

/*
CreateVolumeSnapshotOK describes a response with status code 200, with default header values.

OK
*/
type CreateVolumeSnapshotOK struct {
}

// IsSuccess returns true when this create volume snapshot o k response has a 2xx status code
func (o *CreateVolumeSnapshotOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create volume snapshot o k response has a 3xx status code
func (o *CreateVolumeSnapshotOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create volume snapshot o k response has a 4xx status code
func (o *CreateVolumeSnapshotOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create volume snapshot o k response has a 5xx status code
func (o *CreateVolumeSnapshotOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create volume snapshot o k response a status code equal to that given
func (o *CreateVolumeSnapshotOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create volume snapshot o k response
func (o *CreateVolumeSnapshotOK) Code() int {
	return 200
}

func (o *CreateVolumeSnapshotOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/volumes/{volume_id}/snapshots][%d] createVolumeSnapshotOK ", 200)
}

func (o *CreateVolumeSnapshotOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/volumes/{volume_id}/snapshots][%d] createVolumeSnapshotOK ", 200)
}

func (o *CreateVolumeSnapshotOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
