// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// VolumesCreateReader is a Reader for the VolumesCreate structure.
type VolumesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VolumesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVolumesCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/volumes] Volumes_create", response, response.Code())
	}
}

// NewVolumesCreateOK creates a VolumesCreateOK with default headers values
func NewVolumesCreateOK() *VolumesCreateOK {
	return &VolumesCreateOK{}
}

/*
VolumesCreateOK describes a response with status code 200, with default header values.

OK
*/
type VolumesCreateOK struct {
	Payload *models.Volume
}

// IsSuccess returns true when this volumes create o k response has a 2xx status code
func (o *VolumesCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this volumes create o k response has a 3xx status code
func (o *VolumesCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this volumes create o k response has a 4xx status code
func (o *VolumesCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this volumes create o k response has a 5xx status code
func (o *VolumesCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this volumes create o k response a status code equal to that given
func (o *VolumesCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the volumes create o k response
func (o *VolumesCreateOK) Code() int {
	return 200
}

func (o *VolumesCreateOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/volumes][%d] volumesCreateOK  %+v", 200, o.Payload)
}

func (o *VolumesCreateOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/volumes][%d] volumesCreateOK  %+v", 200, o.Payload)
}

func (o *VolumesCreateOK) GetPayload() *models.Volume {
	return o.Payload
}

func (o *VolumesCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Volume)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
