// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// VolumesGetByIDReader is a Reader for the VolumesGetByID structure.
type VolumesGetByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VolumesGetByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVolumesGetByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app_name}/volumes/{volume_id}] Volumes_get_by_id", response, response.Code())
	}
}

// NewVolumesGetByIDOK creates a VolumesGetByIDOK with default headers values
func NewVolumesGetByIDOK() *VolumesGetByIDOK {
	return &VolumesGetByIDOK{}
}

/*
VolumesGetByIDOK describes a response with status code 200, with default header values.

OK
*/
type VolumesGetByIDOK struct {
	Payload *models.Volume
}

// IsSuccess returns true when this volumes get by Id o k response has a 2xx status code
func (o *VolumesGetByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this volumes get by Id o k response has a 3xx status code
func (o *VolumesGetByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this volumes get by Id o k response has a 4xx status code
func (o *VolumesGetByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this volumes get by Id o k response has a 5xx status code
func (o *VolumesGetByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this volumes get by Id o k response a status code equal to that given
func (o *VolumesGetByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the volumes get by Id o k response
func (o *VolumesGetByIDOK) Code() int {
	return 200
}

func (o *VolumesGetByIDOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/volumes/{volume_id}][%d] volumesGetByIdOK  %+v", 200, o.Payload)
}

func (o *VolumesGetByIDOK) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/volumes/{volume_id}][%d] volumesGetByIdOK  %+v", 200, o.Payload)
}

func (o *VolumesGetByIDOK) GetPayload() *models.Volume {
	return o.Payload
}

func (o *VolumesGetByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Volume)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
