// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// VolumesExtendReader is a Reader for the VolumesExtend structure.
type VolumesExtendReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VolumesExtendReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVolumesExtendOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /apps/{app_name}/volumes/{volume_id}/extend] Volumes_extend", response, response.Code())
	}
}

// NewVolumesExtendOK creates a VolumesExtendOK with default headers values
func NewVolumesExtendOK() *VolumesExtendOK {
	return &VolumesExtendOK{}
}

/*
VolumesExtendOK describes a response with status code 200, with default header values.

OK
*/
type VolumesExtendOK struct {
	Payload *models.ExtendVolumeResponse
}

// IsSuccess returns true when this volumes extend o k response has a 2xx status code
func (o *VolumesExtendOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this volumes extend o k response has a 3xx status code
func (o *VolumesExtendOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this volumes extend o k response has a 4xx status code
func (o *VolumesExtendOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this volumes extend o k response has a 5xx status code
func (o *VolumesExtendOK) IsServerError() bool {
	return false
}

// IsCode returns true when this volumes extend o k response a status code equal to that given
func (o *VolumesExtendOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the volumes extend o k response
func (o *VolumesExtendOK) Code() int {
	return 200
}

func (o *VolumesExtendOK) Error() string {
	return fmt.Sprintf("[PUT /apps/{app_name}/volumes/{volume_id}/extend][%d] volumesExtendOK  %+v", 200, o.Payload)
}

func (o *VolumesExtendOK) String() string {
	return fmt.Sprintf("[PUT /apps/{app_name}/volumes/{volume_id}/extend][%d] volumesExtendOK  %+v", 200, o.Payload)
}

func (o *VolumesExtendOK) GetPayload() *models.ExtendVolumeResponse {
	return o.Payload
}

func (o *VolumesExtendOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExtendVolumeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
