// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVolumesListSnapshotsParams creates a new VolumesListSnapshotsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVolumesListSnapshotsParams() *VolumesListSnapshotsParams {
	return &VolumesListSnapshotsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVolumesListSnapshotsParamsWithTimeout creates a new VolumesListSnapshotsParams object
// with the ability to set a timeout on a request.
func NewVolumesListSnapshotsParamsWithTimeout(timeout time.Duration) *VolumesListSnapshotsParams {
	return &VolumesListSnapshotsParams{
		timeout: timeout,
	}
}

// NewVolumesListSnapshotsParamsWithContext creates a new VolumesListSnapshotsParams object
// with the ability to set a context for a request.
func NewVolumesListSnapshotsParamsWithContext(ctx context.Context) *VolumesListSnapshotsParams {
	return &VolumesListSnapshotsParams{
		Context: ctx,
	}
}

// NewVolumesListSnapshotsParamsWithHTTPClient creates a new VolumesListSnapshotsParams object
// with the ability to set a custom HTTPClient for a request.
func NewVolumesListSnapshotsParamsWithHTTPClient(client *http.Client) *VolumesListSnapshotsParams {
	return &VolumesListSnapshotsParams{
		HTTPClient: client,
	}
}

/*
VolumesListSnapshotsParams contains all the parameters to send to the API endpoint

	for the volumes list snapshots operation.

	Typically these are written to a http.Request.
*/
type VolumesListSnapshotsParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* VolumeID.

	   Volume ID
	*/
	VolumeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the volumes list snapshots params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VolumesListSnapshotsParams) WithDefaults() *VolumesListSnapshotsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the volumes list snapshots params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VolumesListSnapshotsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) WithTimeout(timeout time.Duration) *VolumesListSnapshotsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) WithContext(ctx context.Context) *VolumesListSnapshotsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) WithHTTPClient(client *http.Client) *VolumesListSnapshotsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) WithAppName(appName string) *VolumesListSnapshotsParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithVolumeID adds the volumeID to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) WithVolumeID(volumeID string) *VolumesListSnapshotsParams {
	o.SetVolumeID(volumeID)
	return o
}

// SetVolumeID adds the volumeId to the volumes list snapshots params
func (o *VolumesListSnapshotsParams) SetVolumeID(volumeID string) {
	o.VolumeID = volumeID
}

// WriteToRequest writes these params to a swagger request
func (o *VolumesListSnapshotsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param volume_id
	if err := r.SetPathParam("volume_id", o.VolumeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
