// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewVolumesExtendParams creates a new VolumesExtendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVolumesExtendParams() *VolumesExtendParams {
	return &VolumesExtendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVolumesExtendParamsWithTimeout creates a new VolumesExtendParams object
// with the ability to set a timeout on a request.
func NewVolumesExtendParamsWithTimeout(timeout time.Duration) *VolumesExtendParams {
	return &VolumesExtendParams{
		timeout: timeout,
	}
}

// NewVolumesExtendParamsWithContext creates a new VolumesExtendParams object
// with the ability to set a context for a request.
func NewVolumesExtendParamsWithContext(ctx context.Context) *VolumesExtendParams {
	return &VolumesExtendParams{
		Context: ctx,
	}
}

// NewVolumesExtendParamsWithHTTPClient creates a new VolumesExtendParams object
// with the ability to set a custom HTTPClient for a request.
func NewVolumesExtendParamsWithHTTPClient(client *http.Client) *VolumesExtendParams {
	return &VolumesExtendParams{
		HTTPClient: client,
	}
}

/*
VolumesExtendParams contains all the parameters to send to the API endpoint

	for the volumes extend operation.

	Typically these are written to a http.Request.
*/
type VolumesExtendParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* Request.

	   Request body
	*/
	Request *models.ExtendVolumeRequest

	/* VolumeID.

	   Volume ID
	*/
	VolumeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the volumes extend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VolumesExtendParams) WithDefaults() *VolumesExtendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the volumes extend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VolumesExtendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the volumes extend params
func (o *VolumesExtendParams) WithTimeout(timeout time.Duration) *VolumesExtendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the volumes extend params
func (o *VolumesExtendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the volumes extend params
func (o *VolumesExtendParams) WithContext(ctx context.Context) *VolumesExtendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the volumes extend params
func (o *VolumesExtendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the volumes extend params
func (o *VolumesExtendParams) WithHTTPClient(client *http.Client) *VolumesExtendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the volumes extend params
func (o *VolumesExtendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the volumes extend params
func (o *VolumesExtendParams) WithAppName(appName string) *VolumesExtendParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the volumes extend params
func (o *VolumesExtendParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithRequest adds the request to the volumes extend params
func (o *VolumesExtendParams) WithRequest(request *models.ExtendVolumeRequest) *VolumesExtendParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the volumes extend params
func (o *VolumesExtendParams) SetRequest(request *models.ExtendVolumeRequest) {
	o.Request = request
}

// WithVolumeID adds the volumeID to the volumes extend params
func (o *VolumesExtendParams) WithVolumeID(volumeID string) *VolumesExtendParams {
	o.SetVolumeID(volumeID)
	return o
}

// SetVolumeID adds the volumeId to the volumes extend params
func (o *VolumesExtendParams) SetVolumeID(volumeID string) {
	o.VolumeID = volumeID
}

// WriteToRequest writes these params to a swagger request
func (o *VolumesExtendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param volume_id
	if err := r.SetPathParam("volume_id", o.VolumeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
