// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MachinesDeleteReader is a Reader for the MachinesDelete structure.
type MachinesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /apps/{app_name}/machines/{machine_id}] Machines_delete", response, response.Code())
	}
}

// NewMachinesDeleteOK creates a MachinesDeleteOK with default headers values
func NewMachinesDeleteOK() *MachinesDeleteOK {
	return &MachinesDeleteOK{}
}

/*
MachinesDeleteOK describes a response with status code 200, with default header values.

OK
*/
type MachinesDeleteOK struct {
}

// IsSuccess returns true when this machines delete o k response has a 2xx status code
func (o *MachinesDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines delete o k response has a 3xx status code
func (o *MachinesDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines delete o k response has a 4xx status code
func (o *MachinesDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines delete o k response has a 5xx status code
func (o *MachinesDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines delete o k response a status code equal to that given
func (o *MachinesDeleteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines delete o k response
func (o *MachinesDeleteOK) Code() int {
	return 200
}

func (o *MachinesDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}/machines/{machine_id}][%d] machinesDeleteOK ", 200)
}

func (o *MachinesDeleteOK) String() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}/machines/{machine_id}][%d] machinesDeleteOK ", 200)
}

func (o *MachinesDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
