// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MachinesStartReader is a Reader for the MachinesStart structure.
type MachinesStartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesStartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesStartOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines/{machine_id}/start] Machines_start", response, response.Code())
	}
}

// NewMachinesStartOK creates a MachinesStartOK with default headers values
func NewMachinesStartOK() *MachinesStartOK {
	return &MachinesStartOK{}
}

/*
MachinesStartOK describes a response with status code 200, with default header values.

OK
*/
type MachinesStartOK struct {
}

// IsSuccess returns true when this machines start o k response has a 2xx status code
func (o *MachinesStartOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines start o k response has a 3xx status code
func (o *MachinesStartOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines start o k response has a 4xx status code
func (o *MachinesStartOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines start o k response has a 5xx status code
func (o *MachinesStartOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines start o k response a status code equal to that given
func (o *MachinesStartOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines start o k response
func (o *MachinesStartOK) Code() int {
	return 200
}

func (o *MachinesStartOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/start][%d] machinesStartOK ", 200)
}

func (o *MachinesStartOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/start][%d] machinesStartOK ", 200)
}

func (o *MachinesStartOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
