// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewMachinesCreateParams creates a new MachinesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesCreateParams() *MachinesCreateParams {
	return &MachinesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesCreateParamsWithTimeout creates a new MachinesCreateParams object
// with the ability to set a timeout on a request.
func NewMachinesCreateParamsWithTimeout(timeout time.Duration) *MachinesCreateParams {
	return &MachinesCreateParams{
		timeout: timeout,
	}
}

// NewMachinesCreateParamsWithContext creates a new MachinesCreateParams object
// with the ability to set a context for a request.
func NewMachinesCreateParamsWithContext(ctx context.Context) *MachinesCreateParams {
	return &MachinesCreateParams{
		Context: ctx,
	}
}

// NewMachinesCreateParamsWithHTTPClient creates a new MachinesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesCreateParamsWithHTTPClient(client *http.Client) *MachinesCreateParams {
	return &MachinesCreateParams{
		HTTPClient: client,
	}
}

/*
MachinesCreateParams contains all the parameters to send to the API endpoint

	for the machines create operation.

	Typically these are written to a http.Request.
*/
type MachinesCreateParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* Request.

	   Create machine request
	*/
	Request *models.CreateMachineRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesCreateParams) WithDefaults() *MachinesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines create params
func (o *MachinesCreateParams) WithTimeout(timeout time.Duration) *MachinesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines create params
func (o *MachinesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines create params
func (o *MachinesCreateParams) WithContext(ctx context.Context) *MachinesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines create params
func (o *MachinesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines create params
func (o *MachinesCreateParams) WithHTTPClient(client *http.Client) *MachinesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines create params
func (o *MachinesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines create params
func (o *MachinesCreateParams) WithAppName(appName string) *MachinesCreateParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines create params
func (o *MachinesCreateParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithRequest adds the request to the machines create params
func (o *MachinesCreateParams) WithRequest(request *models.CreateMachineRequest) *MachinesCreateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the machines create params
func (o *MachinesCreateParams) SetRequest(request *models.CreateMachineRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
