// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesCreateLeaseReader is a Reader for the MachinesCreateLease structure.
type MachinesCreateLeaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesCreateLeaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesCreateLeaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines/{machine_id}/lease] Machines_create_lease", response, response.Code())
	}
}

// NewMachinesCreateLeaseOK creates a MachinesCreateLeaseOK with default headers values
func NewMachinesCreateLeaseOK() *MachinesCreateLeaseOK {
	return &MachinesCreateLeaseOK{}
}

/*
MachinesCreateLeaseOK describes a response with status code 200, with default header values.

OK
*/
type MachinesCreateLeaseOK struct {
	Payload *models.Lease
}

// IsSuccess returns true when this machines create lease o k response has a 2xx status code
func (o *MachinesCreateLeaseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines create lease o k response has a 3xx status code
func (o *MachinesCreateLeaseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines create lease o k response has a 4xx status code
func (o *MachinesCreateLeaseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines create lease o k response has a 5xx status code
func (o *MachinesCreateLeaseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines create lease o k response a status code equal to that given
func (o *MachinesCreateLeaseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines create lease o k response
func (o *MachinesCreateLeaseOK) Code() int {
	return 200
}

func (o *MachinesCreateLeaseOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/lease][%d] machinesCreateLeaseOK  %+v", 200, o.Payload)
}

func (o *MachinesCreateLeaseOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/lease][%d] machinesCreateLeaseOK  %+v", 200, o.Payload)
}

func (o *MachinesCreateLeaseOK) GetPayload() *models.Lease {
	return o.Payload
}

func (o *MachinesCreateLeaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Lease)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
