// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesStopReader is a Reader for the MachinesStop structure.
type MachinesStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMachinesStopBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines/{machine_id}/stop] Machines_stop", response, response.Code())
	}
}

// NewMachinesStopOK creates a MachinesStopOK with default headers values
func NewMachinesStopOK() *MachinesStopOK {
	return &MachinesStopOK{}
}

/*
MachinesStopOK describes a response with status code 200, with default header values.

OK
*/
type MachinesStopOK struct {
}

// IsSuccess returns true when this machines stop o k response has a 2xx status code
func (o *MachinesStopOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines stop o k response has a 3xx status code
func (o *MachinesStopOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines stop o k response has a 4xx status code
func (o *MachinesStopOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines stop o k response has a 5xx status code
func (o *MachinesStopOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines stop o k response a status code equal to that given
func (o *MachinesStopOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines stop o k response
func (o *MachinesStopOK) Code() int {
	return 200
}

func (o *MachinesStopOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/stop][%d] machinesStopOK ", 200)
}

func (o *MachinesStopOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/stop][%d] machinesStopOK ", 200)
}

func (o *MachinesStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMachinesStopBadRequest creates a MachinesStopBadRequest with default headers values
func NewMachinesStopBadRequest() *MachinesStopBadRequest {
	return &MachinesStopBadRequest{}
}

/*
MachinesStopBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MachinesStopBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this machines stop bad request response has a 2xx status code
func (o *MachinesStopBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this machines stop bad request response has a 3xx status code
func (o *MachinesStopBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines stop bad request response has a 4xx status code
func (o *MachinesStopBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this machines stop bad request response has a 5xx status code
func (o *MachinesStopBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this machines stop bad request response a status code equal to that given
func (o *MachinesStopBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the machines stop bad request response
func (o *MachinesStopBadRequest) Code() int {
	return 400
}

func (o *MachinesStopBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/stop][%d] machinesStopBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesStopBadRequest) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/stop][%d] machinesStopBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesStopBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MachinesStopBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
