// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MachinesDeleteMetadataReader is a Reader for the MachinesDeleteMetadata structure.
type MachinesDeleteMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesDeleteMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewMachinesDeleteMetadataNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /apps/{app_name}/machines/{machine_id}/metadata/{key}] Machines_delete_metadata", response, response.Code())
	}
}

// NewMachinesDeleteMetadataNoContent creates a MachinesDeleteMetadataNoContent with default headers values
func NewMachinesDeleteMetadataNoContent() *MachinesDeleteMetadataNoContent {
	return &MachinesDeleteMetadataNoContent{}
}

/*
MachinesDeleteMetadataNoContent describes a response with status code 204, with default header values.

No Content
*/
type MachinesDeleteMetadataNoContent struct {
}

// IsSuccess returns true when this machines delete metadata no content response has a 2xx status code
func (o *MachinesDeleteMetadataNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines delete metadata no content response has a 3xx status code
func (o *MachinesDeleteMetadataNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines delete metadata no content response has a 4xx status code
func (o *MachinesDeleteMetadataNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines delete metadata no content response has a 5xx status code
func (o *MachinesDeleteMetadataNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this machines delete metadata no content response a status code equal to that given
func (o *MachinesDeleteMetadataNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the machines delete metadata no content response
func (o *MachinesDeleteMetadataNoContent) Code() int {
	return 204
}

func (o *MachinesDeleteMetadataNoContent) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}/machines/{machine_id}/metadata/{key}][%d] machinesDeleteMetadataNoContent ", 204)
}

func (o *MachinesDeleteMetadataNoContent) String() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}/machines/{machine_id}/metadata/{key}][%d] machinesDeleteMetadataNoContent ", 204)
}

func (o *MachinesDeleteMetadataNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
