// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesListVersionsReader is a Reader for the MachinesListVersions structure.
type MachinesListVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesListVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesListVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app_name}/machines/{machine_id}/versions] Machines_list_versions", response, response.Code())
	}
}

// NewMachinesListVersionsOK creates a MachinesListVersionsOK with default headers values
func NewMachinesListVersionsOK() *MachinesListVersionsOK {
	return &MachinesListVersionsOK{}
}

/*
MachinesListVersionsOK describes a response with status code 200, with default header values.

OK
*/
type MachinesListVersionsOK struct {
	Payload []*models.MachineVersion
}

// IsSuccess returns true when this machines list versions o k response has a 2xx status code
func (o *MachinesListVersionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines list versions o k response has a 3xx status code
func (o *MachinesListVersionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines list versions o k response has a 4xx status code
func (o *MachinesListVersionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines list versions o k response has a 5xx status code
func (o *MachinesListVersionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines list versions o k response a status code equal to that given
func (o *MachinesListVersionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines list versions o k response
func (o *MachinesListVersionsOK) Code() int {
	return 200
}

func (o *MachinesListVersionsOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/versions][%d] machinesListVersionsOK  %+v", 200, o.Payload)
}

func (o *MachinesListVersionsOK) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/versions][%d] machinesListVersionsOK  %+v", 200, o.Payload)
}

func (o *MachinesListVersionsOK) GetPayload() []*models.MachineVersion {
	return o.Payload
}

func (o *MachinesListVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
