// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMachinesReleaseLeaseParams creates a new MachinesReleaseLeaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesReleaseLeaseParams() *MachinesReleaseLeaseParams {
	return &MachinesReleaseLeaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesReleaseLeaseParamsWithTimeout creates a new MachinesReleaseLeaseParams object
// with the ability to set a timeout on a request.
func NewMachinesReleaseLeaseParamsWithTimeout(timeout time.Duration) *MachinesReleaseLeaseParams {
	return &MachinesReleaseLeaseParams{
		timeout: timeout,
	}
}

// NewMachinesReleaseLeaseParamsWithContext creates a new MachinesReleaseLeaseParams object
// with the ability to set a context for a request.
func NewMachinesReleaseLeaseParamsWithContext(ctx context.Context) *MachinesReleaseLeaseParams {
	return &MachinesReleaseLeaseParams{
		Context: ctx,
	}
}

// NewMachinesReleaseLeaseParamsWithHTTPClient creates a new MachinesReleaseLeaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesReleaseLeaseParamsWithHTTPClient(client *http.Client) *MachinesReleaseLeaseParams {
	return &MachinesReleaseLeaseParams{
		HTTPClient: client,
	}
}

/*
MachinesReleaseLeaseParams contains all the parameters to send to the API endpoint

	for the machines release lease operation.

	Typically these are written to a http.Request.
*/
type MachinesReleaseLeaseParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines release lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesReleaseLeaseParams) WithDefaults() *MachinesReleaseLeaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines release lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesReleaseLeaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines release lease params
func (o *MachinesReleaseLeaseParams) WithTimeout(timeout time.Duration) *MachinesReleaseLeaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines release lease params
func (o *MachinesReleaseLeaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines release lease params
func (o *MachinesReleaseLeaseParams) WithContext(ctx context.Context) *MachinesReleaseLeaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines release lease params
func (o *MachinesReleaseLeaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines release lease params
func (o *MachinesReleaseLeaseParams) WithHTTPClient(client *http.Client) *MachinesReleaseLeaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines release lease params
func (o *MachinesReleaseLeaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines release lease params
func (o *MachinesReleaseLeaseParams) WithAppName(appName string) *MachinesReleaseLeaseParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines release lease params
func (o *MachinesReleaseLeaseParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines release lease params
func (o *MachinesReleaseLeaseParams) WithMachineID(machineID string) *MachinesReleaseLeaseParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines release lease params
func (o *MachinesReleaseLeaseParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesReleaseLeaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
