// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesListEventsReader is a Reader for the MachinesListEvents structure.
type MachinesListEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesListEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesListEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app_name}/machines/{machine_id}/events] Machines_list_events", response, response.Code())
	}
}

// NewMachinesListEventsOK creates a MachinesListEventsOK with default headers values
func NewMachinesListEventsOK() *MachinesListEventsOK {
	return &MachinesListEventsOK{}
}

/*
MachinesListEventsOK describes a response with status code 200, with default header values.

OK
*/
type MachinesListEventsOK struct {
	Payload []*models.MachineEvent
}

// IsSuccess returns true when this machines list events o k response has a 2xx status code
func (o *MachinesListEventsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines list events o k response has a 3xx status code
func (o *MachinesListEventsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines list events o k response has a 4xx status code
func (o *MachinesListEventsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines list events o k response has a 5xx status code
func (o *MachinesListEventsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines list events o k response a status code equal to that given
func (o *MachinesListEventsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines list events o k response
func (o *MachinesListEventsOK) Code() int {
	return 200
}

func (o *MachinesListEventsOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/events][%d] machinesListEventsOK  %+v", 200, o.Payload)
}

func (o *MachinesListEventsOK) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/events][%d] machinesListEventsOK  %+v", 200, o.Payload)
}

func (o *MachinesListEventsOK) GetPayload() []*models.MachineEvent {
	return o.Payload
}

func (o *MachinesListEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
