// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewMachinesUpdateParams creates a new MachinesUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesUpdateParams() *MachinesUpdateParams {
	return &MachinesUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesUpdateParamsWithTimeout creates a new MachinesUpdateParams object
// with the ability to set a timeout on a request.
func NewMachinesUpdateParamsWithTimeout(timeout time.Duration) *MachinesUpdateParams {
	return &MachinesUpdateParams{
		timeout: timeout,
	}
}

// NewMachinesUpdateParamsWithContext creates a new MachinesUpdateParams object
// with the ability to set a context for a request.
func NewMachinesUpdateParamsWithContext(ctx context.Context) *MachinesUpdateParams {
	return &MachinesUpdateParams{
		Context: ctx,
	}
}

// NewMachinesUpdateParamsWithHTTPClient creates a new MachinesUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesUpdateParamsWithHTTPClient(client *http.Client) *MachinesUpdateParams {
	return &MachinesUpdateParams{
		HTTPClient: client,
	}
}

/*
MachinesUpdateParams contains all the parameters to send to the API endpoint

	for the machines update operation.

	Typically these are written to a http.Request.
*/
type MachinesUpdateParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	/* Request.

	   Request body
	*/
	Request *models.UpdateMachineRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesUpdateParams) WithDefaults() *MachinesUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines update params
func (o *MachinesUpdateParams) WithTimeout(timeout time.Duration) *MachinesUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines update params
func (o *MachinesUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines update params
func (o *MachinesUpdateParams) WithContext(ctx context.Context) *MachinesUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines update params
func (o *MachinesUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines update params
func (o *MachinesUpdateParams) WithHTTPClient(client *http.Client) *MachinesUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines update params
func (o *MachinesUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines update params
func (o *MachinesUpdateParams) WithAppName(appName string) *MachinesUpdateParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines update params
func (o *MachinesUpdateParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines update params
func (o *MachinesUpdateParams) WithMachineID(machineID string) *MachinesUpdateParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines update params
func (o *MachinesUpdateParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WithRequest adds the request to the machines update params
func (o *MachinesUpdateParams) WithRequest(request *models.UpdateMachineRequest) *MachinesUpdateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the machines update params
func (o *MachinesUpdateParams) SetRequest(request *models.UpdateMachineRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
