// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesShowReader is a Reader for the MachinesShow structure.
type MachinesShowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesShowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesShowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app_name}/machines/{machine_id}] Machines_show", response, response.Code())
	}
}

// NewMachinesShowOK creates a MachinesShowOK with default headers values
func NewMachinesShowOK() *MachinesShowOK {
	return &MachinesShowOK{}
}

/*
MachinesShowOK describes a response with status code 200, with default header values.

OK
*/
type MachinesShowOK struct {
	Payload *models.Machine
}

// IsSuccess returns true when this machines show o k response has a 2xx status code
func (o *MachinesShowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines show o k response has a 3xx status code
func (o *MachinesShowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines show o k response has a 4xx status code
func (o *MachinesShowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines show o k response has a 5xx status code
func (o *MachinesShowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines show o k response a status code equal to that given
func (o *MachinesShowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines show o k response
func (o *MachinesShowOK) Code() int {
	return 200
}

func (o *MachinesShowOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}][%d] machinesShowOK  %+v", 200, o.Payload)
}

func (o *MachinesShowOK) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}][%d] machinesShowOK  %+v", 200, o.Payload)
}

func (o *MachinesShowOK) GetPayload() *models.Machine {
	return o.Payload
}

func (o *MachinesShowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Machine)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
