// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewMachinesExecParams creates a new MachinesExecParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesExecParams() *MachinesExecParams {
	return &MachinesExecParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesExecParamsWithTimeout creates a new MachinesExecParams object
// with the ability to set a timeout on a request.
func NewMachinesExecParamsWithTimeout(timeout time.Duration) *MachinesExecParams {
	return &MachinesExecParams{
		timeout: timeout,
	}
}

// NewMachinesExecParamsWithContext creates a new MachinesExecParams object
// with the ability to set a context for a request.
func NewMachinesExecParamsWithContext(ctx context.Context) *MachinesExecParams {
	return &MachinesExecParams{
		Context: ctx,
	}
}

// NewMachinesExecParamsWithHTTPClient creates a new MachinesExecParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesExecParamsWithHTTPClient(client *http.Client) *MachinesExecParams {
	return &MachinesExecParams{
		HTTPClient: client,
	}
}

/*
MachinesExecParams contains all the parameters to send to the API endpoint

	for the machines exec operation.

	Typically these are written to a http.Request.
*/
type MachinesExecParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	/* Request.

	   Request body
	*/
	Request *models.MachineExecRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines exec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesExecParams) WithDefaults() *MachinesExecParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines exec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesExecParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines exec params
func (o *MachinesExecParams) WithTimeout(timeout time.Duration) *MachinesExecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines exec params
func (o *MachinesExecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines exec params
func (o *MachinesExecParams) WithContext(ctx context.Context) *MachinesExecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines exec params
func (o *MachinesExecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines exec params
func (o *MachinesExecParams) WithHTTPClient(client *http.Client) *MachinesExecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines exec params
func (o *MachinesExecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines exec params
func (o *MachinesExecParams) WithAppName(appName string) *MachinesExecParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines exec params
func (o *MachinesExecParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines exec params
func (o *MachinesExecParams) WithMachineID(machineID string) *MachinesExecParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines exec params
func (o *MachinesExecParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WithRequest adds the request to the machines exec params
func (o *MachinesExecParams) WithRequest(request *models.MachineExecRequest) *MachinesExecParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the machines exec params
func (o *MachinesExecParams) SetRequest(request *models.MachineExecRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesExecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
