// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewMachinesStopParams creates a new MachinesStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesStopParams() *MachinesStopParams {
	return &MachinesStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesStopParamsWithTimeout creates a new MachinesStopParams object
// with the ability to set a timeout on a request.
func NewMachinesStopParamsWithTimeout(timeout time.Duration) *MachinesStopParams {
	return &MachinesStopParams{
		timeout: timeout,
	}
}

// NewMachinesStopParamsWithContext creates a new MachinesStopParams object
// with the ability to set a context for a request.
func NewMachinesStopParamsWithContext(ctx context.Context) *MachinesStopParams {
	return &MachinesStopParams{
		Context: ctx,
	}
}

// NewMachinesStopParamsWithHTTPClient creates a new MachinesStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesStopParamsWithHTTPClient(client *http.Client) *MachinesStopParams {
	return &MachinesStopParams{
		HTTPClient: client,
	}
}

/*
MachinesStopParams contains all the parameters to send to the API endpoint

	for the machines stop operation.

	Typically these are written to a http.Request.
*/
type MachinesStopParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	/* Request.

	   Optional request body
	*/
	Request *models.StopRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesStopParams) WithDefaults() *MachinesStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines stop params
func (o *MachinesStopParams) WithTimeout(timeout time.Duration) *MachinesStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines stop params
func (o *MachinesStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines stop params
func (o *MachinesStopParams) WithContext(ctx context.Context) *MachinesStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines stop params
func (o *MachinesStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines stop params
func (o *MachinesStopParams) WithHTTPClient(client *http.Client) *MachinesStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines stop params
func (o *MachinesStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines stop params
func (o *MachinesStopParams) WithAppName(appName string) *MachinesStopParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines stop params
func (o *MachinesStopParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines stop params
func (o *MachinesStopParams) WithMachineID(machineID string) *MachinesStopParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines stop params
func (o *MachinesStopParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WithRequest adds the request to the machines stop params
func (o *MachinesStopParams) WithRequest(request *models.StopRequest) *MachinesStopParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the machines stop params
func (o *MachinesStopParams) SetRequest(request *models.StopRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
