// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MachinesReleaseLeaseReader is a Reader for the MachinesReleaseLease structure.
type MachinesReleaseLeaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesReleaseLeaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesReleaseLeaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /apps/{app_name}/machines/{machine_id}/lease] Machines_release_lease", response, response.Code())
	}
}

// NewMachinesReleaseLeaseOK creates a MachinesReleaseLeaseOK with default headers values
func NewMachinesReleaseLeaseOK() *MachinesReleaseLeaseOK {
	return &MachinesReleaseLeaseOK{}
}

/*
MachinesReleaseLeaseOK describes a response with status code 200, with default header values.

OK
*/
type MachinesReleaseLeaseOK struct {
}

// IsSuccess returns true when this machines release lease o k response has a 2xx status code
func (o *MachinesReleaseLeaseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines release lease o k response has a 3xx status code
func (o *MachinesReleaseLeaseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines release lease o k response has a 4xx status code
func (o *MachinesReleaseLeaseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines release lease o k response has a 5xx status code
func (o *MachinesReleaseLeaseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines release lease o k response a status code equal to that given
func (o *MachinesReleaseLeaseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines release lease o k response
func (o *MachinesReleaseLeaseOK) Code() int {
	return 200
}

func (o *MachinesReleaseLeaseOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}/machines/{machine_id}/lease][%d] machinesReleaseLeaseOK ", 200)
}

func (o *MachinesReleaseLeaseOK) String() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}/machines/{machine_id}/lease][%d] machinesReleaseLeaseOK ", 200)
}

func (o *MachinesReleaseLeaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
