// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMachinesCordonParams creates a new MachinesCordonParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesCordonParams() *MachinesCordonParams {
	return &MachinesCordonParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesCordonParamsWithTimeout creates a new MachinesCordonParams object
// with the ability to set a timeout on a request.
func NewMachinesCordonParamsWithTimeout(timeout time.Duration) *MachinesCordonParams {
	return &MachinesCordonParams{
		timeout: timeout,
	}
}

// NewMachinesCordonParamsWithContext creates a new MachinesCordonParams object
// with the ability to set a context for a request.
func NewMachinesCordonParamsWithContext(ctx context.Context) *MachinesCordonParams {
	return &MachinesCordonParams{
		Context: ctx,
	}
}

// NewMachinesCordonParamsWithHTTPClient creates a new MachinesCordonParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesCordonParamsWithHTTPClient(client *http.Client) *MachinesCordonParams {
	return &MachinesCordonParams{
		HTTPClient: client,
	}
}

/*
MachinesCordonParams contains all the parameters to send to the API endpoint

	for the machines cordon operation.

	Typically these are written to a http.Request.
*/
type MachinesCordonParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines cordon params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesCordonParams) WithDefaults() *MachinesCordonParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines cordon params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesCordonParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines cordon params
func (o *MachinesCordonParams) WithTimeout(timeout time.Duration) *MachinesCordonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines cordon params
func (o *MachinesCordonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines cordon params
func (o *MachinesCordonParams) WithContext(ctx context.Context) *MachinesCordonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines cordon params
func (o *MachinesCordonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines cordon params
func (o *MachinesCordonParams) WithHTTPClient(client *http.Client) *MachinesCordonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines cordon params
func (o *MachinesCordonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines cordon params
func (o *MachinesCordonParams) WithAppName(appName string) *MachinesCordonParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines cordon params
func (o *MachinesCordonParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines cordon params
func (o *MachinesCordonParams) WithMachineID(machineID string) *MachinesCordonParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines cordon params
func (o *MachinesCordonParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesCordonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
