// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesListProcessesReader is a Reader for the MachinesListProcesses structure.
type MachinesListProcessesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesListProcessesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesListProcessesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMachinesListProcessesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app_name}/machines/{machine_id}/ps] Machines_list_processes", response, response.Code())
	}
}

// NewMachinesListProcessesOK creates a MachinesListProcessesOK with default headers values
func NewMachinesListProcessesOK() *MachinesListProcessesOK {
	return &MachinesListProcessesOK{}
}

/*
MachinesListProcessesOK describes a response with status code 200, with default header values.

OK
*/
type MachinesListProcessesOK struct {
	Payload []*models.ProcessStat
}

// IsSuccess returns true when this machines list processes o k response has a 2xx status code
func (o *MachinesListProcessesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines list processes o k response has a 3xx status code
func (o *MachinesListProcessesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines list processes o k response has a 4xx status code
func (o *MachinesListProcessesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines list processes o k response has a 5xx status code
func (o *MachinesListProcessesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines list processes o k response a status code equal to that given
func (o *MachinesListProcessesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines list processes o k response
func (o *MachinesListProcessesOK) Code() int {
	return 200
}

func (o *MachinesListProcessesOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/ps][%d] machinesListProcessesOK  %+v", 200, o.Payload)
}

func (o *MachinesListProcessesOK) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/ps][%d] machinesListProcessesOK  %+v", 200, o.Payload)
}

func (o *MachinesListProcessesOK) GetPayload() []*models.ProcessStat {
	return o.Payload
}

func (o *MachinesListProcessesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMachinesListProcessesBadRequest creates a MachinesListProcessesBadRequest with default headers values
func NewMachinesListProcessesBadRequest() *MachinesListProcessesBadRequest {
	return &MachinesListProcessesBadRequest{}
}

/*
MachinesListProcessesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MachinesListProcessesBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this machines list processes bad request response has a 2xx status code
func (o *MachinesListProcessesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this machines list processes bad request response has a 3xx status code
func (o *MachinesListProcessesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines list processes bad request response has a 4xx status code
func (o *MachinesListProcessesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this machines list processes bad request response has a 5xx status code
func (o *MachinesListProcessesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this machines list processes bad request response a status code equal to that given
func (o *MachinesListProcessesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the machines list processes bad request response
func (o *MachinesListProcessesBadRequest) Code() int {
	return 400
}

func (o *MachinesListProcessesBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/ps][%d] machinesListProcessesBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesListProcessesBadRequest) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/ps][%d] machinesListProcessesBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesListProcessesBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MachinesListProcessesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
