// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesWaitReader is a Reader for the MachinesWait structure.
type MachinesWaitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesWaitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesWaitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMachinesWaitBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app_name}/machines/{machine_id}/wait] Machines_wait", response, response.Code())
	}
}

// NewMachinesWaitOK creates a MachinesWaitOK with default headers values
func NewMachinesWaitOK() *MachinesWaitOK {
	return &MachinesWaitOK{}
}

/*
MachinesWaitOK describes a response with status code 200, with default header values.

OK
*/
type MachinesWaitOK struct {
}

// IsSuccess returns true when this machines wait o k response has a 2xx status code
func (o *MachinesWaitOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines wait o k response has a 3xx status code
func (o *MachinesWaitOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines wait o k response has a 4xx status code
func (o *MachinesWaitOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines wait o k response has a 5xx status code
func (o *MachinesWaitOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines wait o k response a status code equal to that given
func (o *MachinesWaitOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines wait o k response
func (o *MachinesWaitOK) Code() int {
	return 200
}

func (o *MachinesWaitOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/wait][%d] machinesWaitOK ", 200)
}

func (o *MachinesWaitOK) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/wait][%d] machinesWaitOK ", 200)
}

func (o *MachinesWaitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMachinesWaitBadRequest creates a MachinesWaitBadRequest with default headers values
func NewMachinesWaitBadRequest() *MachinesWaitBadRequest {
	return &MachinesWaitBadRequest{}
}

/*
MachinesWaitBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MachinesWaitBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this machines wait bad request response has a 2xx status code
func (o *MachinesWaitBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this machines wait bad request response has a 3xx status code
func (o *MachinesWaitBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines wait bad request response has a 4xx status code
func (o *MachinesWaitBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this machines wait bad request response has a 5xx status code
func (o *MachinesWaitBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this machines wait bad request response a status code equal to that given
func (o *MachinesWaitBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the machines wait bad request response
func (o *MachinesWaitBadRequest) Code() int {
	return 400
}

func (o *MachinesWaitBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/wait][%d] machinesWaitBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesWaitBadRequest) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/wait][%d] machinesWaitBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesWaitBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MachinesWaitBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
