// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesUpdateMetadataReader is a Reader for the MachinesUpdateMetadata structure.
type MachinesUpdateMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesUpdateMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewMachinesUpdateMetadataNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMachinesUpdateMetadataBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines/{machine_id}/metadata/{key}] Machines_update_metadata", response, response.Code())
	}
}

// NewMachinesUpdateMetadataNoContent creates a MachinesUpdateMetadataNoContent with default headers values
func NewMachinesUpdateMetadataNoContent() *MachinesUpdateMetadataNoContent {
	return &MachinesUpdateMetadataNoContent{}
}

/*
MachinesUpdateMetadataNoContent describes a response with status code 204, with default header values.

No Content
*/
type MachinesUpdateMetadataNoContent struct {
}

// IsSuccess returns true when this machines update metadata no content response has a 2xx status code
func (o *MachinesUpdateMetadataNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines update metadata no content response has a 3xx status code
func (o *MachinesUpdateMetadataNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines update metadata no content response has a 4xx status code
func (o *MachinesUpdateMetadataNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines update metadata no content response has a 5xx status code
func (o *MachinesUpdateMetadataNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this machines update metadata no content response a status code equal to that given
func (o *MachinesUpdateMetadataNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the machines update metadata no content response
func (o *MachinesUpdateMetadataNoContent) Code() int {
	return 204
}

func (o *MachinesUpdateMetadataNoContent) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/metadata/{key}][%d] machinesUpdateMetadataNoContent ", 204)
}

func (o *MachinesUpdateMetadataNoContent) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/metadata/{key}][%d] machinesUpdateMetadataNoContent ", 204)
}

func (o *MachinesUpdateMetadataNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMachinesUpdateMetadataBadRequest creates a MachinesUpdateMetadataBadRequest with default headers values
func NewMachinesUpdateMetadataBadRequest() *MachinesUpdateMetadataBadRequest {
	return &MachinesUpdateMetadataBadRequest{}
}

/*
MachinesUpdateMetadataBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MachinesUpdateMetadataBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this machines update metadata bad request response has a 2xx status code
func (o *MachinesUpdateMetadataBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this machines update metadata bad request response has a 3xx status code
func (o *MachinesUpdateMetadataBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines update metadata bad request response has a 4xx status code
func (o *MachinesUpdateMetadataBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this machines update metadata bad request response has a 5xx status code
func (o *MachinesUpdateMetadataBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this machines update metadata bad request response a status code equal to that given
func (o *MachinesUpdateMetadataBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the machines update metadata bad request response
func (o *MachinesUpdateMetadataBadRequest) Code() int {
	return 400
}

func (o *MachinesUpdateMetadataBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/metadata/{key}][%d] machinesUpdateMetadataBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesUpdateMetadataBadRequest) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/metadata/{key}][%d] machinesUpdateMetadataBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesUpdateMetadataBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MachinesUpdateMetadataBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
