// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesCreateReader is a Reader for the MachinesCreate structure.
type MachinesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines] Machines_create", response, response.Code())
	}
}

// NewMachinesCreateOK creates a MachinesCreateOK with default headers values
func NewMachinesCreateOK() *MachinesCreateOK {
	return &MachinesCreateOK{}
}

/*
MachinesCreateOK describes a response with status code 200, with default header values.

OK
*/
type MachinesCreateOK struct {
	Payload *models.Machine
}

// IsSuccess returns true when this machines create o k response has a 2xx status code
func (o *MachinesCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines create o k response has a 3xx status code
func (o *MachinesCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines create o k response has a 4xx status code
func (o *MachinesCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines create o k response has a 5xx status code
func (o *MachinesCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines create o k response a status code equal to that given
func (o *MachinesCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines create o k response
func (o *MachinesCreateOK) Code() int {
	return 200
}

func (o *MachinesCreateOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines][%d] machinesCreateOK  %+v", 200, o.Payload)
}

func (o *MachinesCreateOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines][%d] machinesCreateOK  %+v", 200, o.Payload)
}

func (o *MachinesCreateOK) GetPayload() *models.Machine {
	return o.Payload
}

func (o *MachinesCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Machine)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
