// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewMachinesListParams creates a new MachinesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesListParams() *MachinesListParams {
	return &MachinesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesListParamsWithTimeout creates a new MachinesListParams object
// with the ability to set a timeout on a request.
func NewMachinesListParamsWithTimeout(timeout time.Duration) *MachinesListParams {
	return &MachinesListParams{
		timeout: timeout,
	}
}

// NewMachinesListParamsWithContext creates a new MachinesListParams object
// with the ability to set a context for a request.
func NewMachinesListParamsWithContext(ctx context.Context) *MachinesListParams {
	return &MachinesListParams{
		Context: ctx,
	}
}

// NewMachinesListParamsWithHTTPClient creates a new MachinesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesListParamsWithHTTPClient(client *http.Client) *MachinesListParams {
	return &MachinesListParams{
		HTTPClient: client,
	}
}

/*
MachinesListParams contains all the parameters to send to the API endpoint

	for the machines list operation.

	Typically these are written to a http.Request.
*/
type MachinesListParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* IncludeDeleted.

	   Include deleted machines
	*/
	IncludeDeleted *bool

	/* Region.

	   Region filter
	*/
	Region *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesListParams) WithDefaults() *MachinesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines list params
func (o *MachinesListParams) WithTimeout(timeout time.Duration) *MachinesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines list params
func (o *MachinesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines list params
func (o *MachinesListParams) WithContext(ctx context.Context) *MachinesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines list params
func (o *MachinesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines list params
func (o *MachinesListParams) WithHTTPClient(client *http.Client) *MachinesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines list params
func (o *MachinesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines list params
func (o *MachinesListParams) WithAppName(appName string) *MachinesListParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines list params
func (o *MachinesListParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithIncludeDeleted adds the includeDeleted to the machines list params
func (o *MachinesListParams) WithIncludeDeleted(includeDeleted *bool) *MachinesListParams {
	o.SetIncludeDeleted(includeDeleted)
	return o
}

// SetIncludeDeleted adds the includeDeleted to the machines list params
func (o *MachinesListParams) SetIncludeDeleted(includeDeleted *bool) {
	o.IncludeDeleted = includeDeleted
}

// WithRegion adds the region to the machines list params
func (o *MachinesListParams) WithRegion(region *string) *MachinesListParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the machines list params
func (o *MachinesListParams) SetRegion(region *string) {
	o.Region = region
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	if o.IncludeDeleted != nil {

		// query param include_deleted
		var qrIncludeDeleted bool

		if o.IncludeDeleted != nil {
			qrIncludeDeleted = *o.IncludeDeleted
		}
		qIncludeDeleted := swag.FormatBool(qrIncludeDeleted)
		if qIncludeDeleted != "" {

			if err := r.SetQueryParam("include_deleted", qIncludeDeleted); err != nil {
				return err
			}
		}
	}

	if o.Region != nil {

		// query param region
		var qrRegion string

		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {

			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
