// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewMachinesSignalParams creates a new MachinesSignalParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesSignalParams() *MachinesSignalParams {
	return &MachinesSignalParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesSignalParamsWithTimeout creates a new MachinesSignalParams object
// with the ability to set a timeout on a request.
func NewMachinesSignalParamsWithTimeout(timeout time.Duration) *MachinesSignalParams {
	return &MachinesSignalParams{
		timeout: timeout,
	}
}

// NewMachinesSignalParamsWithContext creates a new MachinesSignalParams object
// with the ability to set a context for a request.
func NewMachinesSignalParamsWithContext(ctx context.Context) *MachinesSignalParams {
	return &MachinesSignalParams{
		Context: ctx,
	}
}

// NewMachinesSignalParamsWithHTTPClient creates a new MachinesSignalParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesSignalParamsWithHTTPClient(client *http.Client) *MachinesSignalParams {
	return &MachinesSignalParams{
		HTTPClient: client,
	}
}

/*
MachinesSignalParams contains all the parameters to send to the API endpoint

	for the machines signal operation.

	Typically these are written to a http.Request.
*/
type MachinesSignalParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	/* Request.

	   Request body
	*/
	Request *models.SignalRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines signal params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesSignalParams) WithDefaults() *MachinesSignalParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines signal params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesSignalParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines signal params
func (o *MachinesSignalParams) WithTimeout(timeout time.Duration) *MachinesSignalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines signal params
func (o *MachinesSignalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines signal params
func (o *MachinesSignalParams) WithContext(ctx context.Context) *MachinesSignalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines signal params
func (o *MachinesSignalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines signal params
func (o *MachinesSignalParams) WithHTTPClient(client *http.Client) *MachinesSignalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines signal params
func (o *MachinesSignalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines signal params
func (o *MachinesSignalParams) WithAppName(appName string) *MachinesSignalParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines signal params
func (o *MachinesSignalParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines signal params
func (o *MachinesSignalParams) WithMachineID(machineID string) *MachinesSignalParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines signal params
func (o *MachinesSignalParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WithRequest adds the request to the machines signal params
func (o *MachinesSignalParams) WithRequest(request *models.SignalRequest) *MachinesSignalParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the machines signal params
func (o *MachinesSignalParams) SetRequest(request *models.SignalRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesSignalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
