// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewMachinesCreateLeaseParams creates a new MachinesCreateLeaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesCreateLeaseParams() *MachinesCreateLeaseParams {
	return &MachinesCreateLeaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesCreateLeaseParamsWithTimeout creates a new MachinesCreateLeaseParams object
// with the ability to set a timeout on a request.
func NewMachinesCreateLeaseParamsWithTimeout(timeout time.Duration) *MachinesCreateLeaseParams {
	return &MachinesCreateLeaseParams{
		timeout: timeout,
	}
}

// NewMachinesCreateLeaseParamsWithContext creates a new MachinesCreateLeaseParams object
// with the ability to set a context for a request.
func NewMachinesCreateLeaseParamsWithContext(ctx context.Context) *MachinesCreateLeaseParams {
	return &MachinesCreateLeaseParams{
		Context: ctx,
	}
}

// NewMachinesCreateLeaseParamsWithHTTPClient creates a new MachinesCreateLeaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesCreateLeaseParamsWithHTTPClient(client *http.Client) *MachinesCreateLeaseParams {
	return &MachinesCreateLeaseParams{
		HTTPClient: client,
	}
}

/*
MachinesCreateLeaseParams contains all the parameters to send to the API endpoint

	for the machines create lease operation.

	Typically these are written to a http.Request.
*/
type MachinesCreateLeaseParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	/* Request.

	   Request body
	*/
	Request *models.CreateLeaseRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines create lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesCreateLeaseParams) WithDefaults() *MachinesCreateLeaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines create lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesCreateLeaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines create lease params
func (o *MachinesCreateLeaseParams) WithTimeout(timeout time.Duration) *MachinesCreateLeaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines create lease params
func (o *MachinesCreateLeaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines create lease params
func (o *MachinesCreateLeaseParams) WithContext(ctx context.Context) *MachinesCreateLeaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines create lease params
func (o *MachinesCreateLeaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines create lease params
func (o *MachinesCreateLeaseParams) WithHTTPClient(client *http.Client) *MachinesCreateLeaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines create lease params
func (o *MachinesCreateLeaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines create lease params
func (o *MachinesCreateLeaseParams) WithAppName(appName string) *MachinesCreateLeaseParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines create lease params
func (o *MachinesCreateLeaseParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines create lease params
func (o *MachinesCreateLeaseParams) WithMachineID(machineID string) *MachinesCreateLeaseParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines create lease params
func (o *MachinesCreateLeaseParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WithRequest adds the request to the machines create lease params
func (o *MachinesCreateLeaseParams) WithRequest(request *models.CreateLeaseRequest) *MachinesCreateLeaseParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the machines create lease params
func (o *MachinesCreateLeaseParams) SetRequest(request *models.CreateLeaseRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesCreateLeaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
