// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMachinesUpdateMetadataParams creates a new MachinesUpdateMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesUpdateMetadataParams() *MachinesUpdateMetadataParams {
	return &MachinesUpdateMetadataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesUpdateMetadataParamsWithTimeout creates a new MachinesUpdateMetadataParams object
// with the ability to set a timeout on a request.
func NewMachinesUpdateMetadataParamsWithTimeout(timeout time.Duration) *MachinesUpdateMetadataParams {
	return &MachinesUpdateMetadataParams{
		timeout: timeout,
	}
}

// NewMachinesUpdateMetadataParamsWithContext creates a new MachinesUpdateMetadataParams object
// with the ability to set a context for a request.
func NewMachinesUpdateMetadataParamsWithContext(ctx context.Context) *MachinesUpdateMetadataParams {
	return &MachinesUpdateMetadataParams{
		Context: ctx,
	}
}

// NewMachinesUpdateMetadataParamsWithHTTPClient creates a new MachinesUpdateMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesUpdateMetadataParamsWithHTTPClient(client *http.Client) *MachinesUpdateMetadataParams {
	return &MachinesUpdateMetadataParams{
		HTTPClient: client,
	}
}

/*
MachinesUpdateMetadataParams contains all the parameters to send to the API endpoint

	for the machines update metadata operation.

	Typically these are written to a http.Request.
*/
type MachinesUpdateMetadataParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* Key.

	   Metadata Key
	*/
	Key string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines update metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesUpdateMetadataParams) WithDefaults() *MachinesUpdateMetadataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines update metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesUpdateMetadataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines update metadata params
func (o *MachinesUpdateMetadataParams) WithTimeout(timeout time.Duration) *MachinesUpdateMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines update metadata params
func (o *MachinesUpdateMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines update metadata params
func (o *MachinesUpdateMetadataParams) WithContext(ctx context.Context) *MachinesUpdateMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines update metadata params
func (o *MachinesUpdateMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines update metadata params
func (o *MachinesUpdateMetadataParams) WithHTTPClient(client *http.Client) *MachinesUpdateMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines update metadata params
func (o *MachinesUpdateMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines update metadata params
func (o *MachinesUpdateMetadataParams) WithAppName(appName string) *MachinesUpdateMetadataParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines update metadata params
func (o *MachinesUpdateMetadataParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithKey adds the key to the machines update metadata params
func (o *MachinesUpdateMetadataParams) WithKey(key string) *MachinesUpdateMetadataParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the machines update metadata params
func (o *MachinesUpdateMetadataParams) SetKey(key string) {
	o.Key = key
}

// WithMachineID adds the machineID to the machines update metadata params
func (o *MachinesUpdateMetadataParams) WithMachineID(machineID string) *MachinesUpdateMetadataParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines update metadata params
func (o *MachinesUpdateMetadataParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesUpdateMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
