// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMachinesListVersionsParams creates a new MachinesListVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesListVersionsParams() *MachinesListVersionsParams {
	return &MachinesListVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesListVersionsParamsWithTimeout creates a new MachinesListVersionsParams object
// with the ability to set a timeout on a request.
func NewMachinesListVersionsParamsWithTimeout(timeout time.Duration) *MachinesListVersionsParams {
	return &MachinesListVersionsParams{
		timeout: timeout,
	}
}

// NewMachinesListVersionsParamsWithContext creates a new MachinesListVersionsParams object
// with the ability to set a context for a request.
func NewMachinesListVersionsParamsWithContext(ctx context.Context) *MachinesListVersionsParams {
	return &MachinesListVersionsParams{
		Context: ctx,
	}
}

// NewMachinesListVersionsParamsWithHTTPClient creates a new MachinesListVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesListVersionsParamsWithHTTPClient(client *http.Client) *MachinesListVersionsParams {
	return &MachinesListVersionsParams{
		HTTPClient: client,
	}
}

/*
MachinesListVersionsParams contains all the parameters to send to the API endpoint

	for the machines list versions operation.

	Typically these are written to a http.Request.
*/
type MachinesListVersionsParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines list versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesListVersionsParams) WithDefaults() *MachinesListVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines list versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesListVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines list versions params
func (o *MachinesListVersionsParams) WithTimeout(timeout time.Duration) *MachinesListVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines list versions params
func (o *MachinesListVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines list versions params
func (o *MachinesListVersionsParams) WithContext(ctx context.Context) *MachinesListVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines list versions params
func (o *MachinesListVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines list versions params
func (o *MachinesListVersionsParams) WithHTTPClient(client *http.Client) *MachinesListVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines list versions params
func (o *MachinesListVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines list versions params
func (o *MachinesListVersionsParams) WithAppName(appName string) *MachinesListVersionsParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines list versions params
func (o *MachinesListVersionsParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines list versions params
func (o *MachinesListVersionsParams) WithMachineID(machineID string) *MachinesListVersionsParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines list versions params
func (o *MachinesListVersionsParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesListVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
