// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesRestartReader is a Reader for the MachinesRestart structure.
type MachinesRestartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesRestartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesRestartOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMachinesRestartBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines/{machine_id}/restart] Machines_restart", response, response.Code())
	}
}

// NewMachinesRestartOK creates a MachinesRestartOK with default headers values
func NewMachinesRestartOK() *MachinesRestartOK {
	return &MachinesRestartOK{}
}

/*
MachinesRestartOK describes a response with status code 200, with default header values.

OK
*/
type MachinesRestartOK struct {
}

// IsSuccess returns true when this machines restart o k response has a 2xx status code
func (o *MachinesRestartOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines restart o k response has a 3xx status code
func (o *MachinesRestartOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines restart o k response has a 4xx status code
func (o *MachinesRestartOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines restart o k response has a 5xx status code
func (o *MachinesRestartOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines restart o k response a status code equal to that given
func (o *MachinesRestartOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines restart o k response
func (o *MachinesRestartOK) Code() int {
	return 200
}

func (o *MachinesRestartOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/restart][%d] machinesRestartOK ", 200)
}

func (o *MachinesRestartOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/restart][%d] machinesRestartOK ", 200)
}

func (o *MachinesRestartOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMachinesRestartBadRequest creates a MachinesRestartBadRequest with default headers values
func NewMachinesRestartBadRequest() *MachinesRestartBadRequest {
	return &MachinesRestartBadRequest{}
}

/*
MachinesRestartBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MachinesRestartBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this machines restart bad request response has a 2xx status code
func (o *MachinesRestartBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this machines restart bad request response has a 3xx status code
func (o *MachinesRestartBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines restart bad request response has a 4xx status code
func (o *MachinesRestartBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this machines restart bad request response has a 5xx status code
func (o *MachinesRestartBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this machines restart bad request response a status code equal to that given
func (o *MachinesRestartBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the machines restart bad request response
func (o *MachinesRestartBadRequest) Code() int {
	return 400
}

func (o *MachinesRestartBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/restart][%d] machinesRestartBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesRestartBadRequest) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/restart][%d] machinesRestartBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesRestartBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MachinesRestartBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
