// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMachinesRestartParams creates a new MachinesRestartParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesRestartParams() *MachinesRestartParams {
	return &MachinesRestartParams{
		requestTimeout: cr.DefaultTimeout,
	}
}

// NewMachinesRestartParamsWithTimeout creates a new MachinesRestartParams object
// with the ability to set a timeout on a request.
func NewMachinesRestartParamsWithTimeout(timeout time.Duration) *MachinesRestartParams {
	return &MachinesRestartParams{
		requestTimeout: timeout,
	}
}

// NewMachinesRestartParamsWithContext creates a new MachinesRestartParams object
// with the ability to set a context for a request.
func NewMachinesRestartParamsWithContext(ctx context.Context) *MachinesRestartParams {
	return &MachinesRestartParams{
		Context: ctx,
	}
}

// NewMachinesRestartParamsWithHTTPClient creates a new MachinesRestartParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesRestartParamsWithHTTPClient(client *http.Client) *MachinesRestartParams {
	return &MachinesRestartParams{
		HTTPClient: client,
	}
}

/*
MachinesRestartParams contains all the parameters to send to the API endpoint

	for the machines restart operation.

	Typically these are written to a http.Request.
*/
type MachinesRestartParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	/* Timeout.

	   Restart timeout as a Go duration string or number of seconds
	*/
	Timeout *string

	requestTimeout time.Duration
	Context        context.Context
	HTTPClient     *http.Client
}

// WithDefaults hydrates default values in the machines restart params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesRestartParams) WithDefaults() *MachinesRestartParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines restart params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesRestartParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithRequestTimeout adds the timeout to the machines restart params
func (o *MachinesRestartParams) WithRequestTimeout(timeout time.Duration) *MachinesRestartParams {
	o.SetRequestTimeout(timeout)
	return o
}

// SetRequestTimeout adds the timeout to the machines restart params
func (o *MachinesRestartParams) SetRequestTimeout(timeout time.Duration) {
	o.requestTimeout = timeout
}

// WithContext adds the context to the machines restart params
func (o *MachinesRestartParams) WithContext(ctx context.Context) *MachinesRestartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines restart params
func (o *MachinesRestartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines restart params
func (o *MachinesRestartParams) WithHTTPClient(client *http.Client) *MachinesRestartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines restart params
func (o *MachinesRestartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines restart params
func (o *MachinesRestartParams) WithAppName(appName string) *MachinesRestartParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines restart params
func (o *MachinesRestartParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines restart params
func (o *MachinesRestartParams) WithMachineID(machineID string) *MachinesRestartParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines restart params
func (o *MachinesRestartParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WithTimeout adds the timeout to the machines restart params
func (o *MachinesRestartParams) WithTimeout(timeout *string) *MachinesRestartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines restart params
func (o *MachinesRestartParams) SetTimeout(timeout *string) {
	o.Timeout = timeout
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesRestartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.requestTimeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}

	if o.Timeout != nil {

		// query param timeout
		var qrTimeout string

		if o.Timeout != nil {
			qrTimeout = *o.Timeout
		}
		qTimeout := qrTimeout
		if qTimeout != "" {

			if err := r.SetQueryParam("timeout", qTimeout); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
