// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesShowLeaseReader is a Reader for the MachinesShowLease structure.
type MachinesShowLeaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesShowLeaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesShowLeaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app_name}/machines/{machine_id}/lease] Machines_show_lease", response, response.Code())
	}
}

// NewMachinesShowLeaseOK creates a MachinesShowLeaseOK with default headers values
func NewMachinesShowLeaseOK() *MachinesShowLeaseOK {
	return &MachinesShowLeaseOK{}
}

/*
MachinesShowLeaseOK describes a response with status code 200, with default header values.

OK
*/
type MachinesShowLeaseOK struct {
	Payload *models.Lease
}

// IsSuccess returns true when this machines show lease o k response has a 2xx status code
func (o *MachinesShowLeaseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines show lease o k response has a 3xx status code
func (o *MachinesShowLeaseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines show lease o k response has a 4xx status code
func (o *MachinesShowLeaseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines show lease o k response has a 5xx status code
func (o *MachinesShowLeaseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines show lease o k response a status code equal to that given
func (o *MachinesShowLeaseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines show lease o k response
func (o *MachinesShowLeaseOK) Code() int {
	return 200
}

func (o *MachinesShowLeaseOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/lease][%d] machinesShowLeaseOK  %+v", 200, o.Payload)
}

func (o *MachinesShowLeaseOK) String() string {
	return fmt.Sprintf("[GET /apps/{app_name}/machines/{machine_id}/lease][%d] machinesShowLeaseOK  %+v", 200, o.Payload)
}

func (o *MachinesShowLeaseOK) GetPayload() *models.Lease {
	return o.Payload
}

func (o *MachinesShowLeaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Lease)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
