// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMachinesDeleteMetadataParams creates a new MachinesDeleteMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesDeleteMetadataParams() *MachinesDeleteMetadataParams {
	return &MachinesDeleteMetadataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesDeleteMetadataParamsWithTimeout creates a new MachinesDeleteMetadataParams object
// with the ability to set a timeout on a request.
func NewMachinesDeleteMetadataParamsWithTimeout(timeout time.Duration) *MachinesDeleteMetadataParams {
	return &MachinesDeleteMetadataParams{
		timeout: timeout,
	}
}

// NewMachinesDeleteMetadataParamsWithContext creates a new MachinesDeleteMetadataParams object
// with the ability to set a context for a request.
func NewMachinesDeleteMetadataParamsWithContext(ctx context.Context) *MachinesDeleteMetadataParams {
	return &MachinesDeleteMetadataParams{
		Context: ctx,
	}
}

// NewMachinesDeleteMetadataParamsWithHTTPClient creates a new MachinesDeleteMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesDeleteMetadataParamsWithHTTPClient(client *http.Client) *MachinesDeleteMetadataParams {
	return &MachinesDeleteMetadataParams{
		HTTPClient: client,
	}
}

/*
MachinesDeleteMetadataParams contains all the parameters to send to the API endpoint

	for the machines delete metadata operation.

	Typically these are written to a http.Request.
*/
type MachinesDeleteMetadataParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* Key.

	   Metadata Key
	*/
	Key string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines delete metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesDeleteMetadataParams) WithDefaults() *MachinesDeleteMetadataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines delete metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesDeleteMetadataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) WithTimeout(timeout time.Duration) *MachinesDeleteMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) WithContext(ctx context.Context) *MachinesDeleteMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) WithHTTPClient(client *http.Client) *MachinesDeleteMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) WithAppName(appName string) *MachinesDeleteMetadataParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithKey adds the key to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) WithKey(key string) *MachinesDeleteMetadataParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) SetKey(key string) {
	o.Key = key
}

// WithMachineID adds the machineID to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) WithMachineID(machineID string) *MachinesDeleteMetadataParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines delete metadata params
func (o *MachinesDeleteMetadataParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesDeleteMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
