// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MachinesCordonReader is a Reader for the MachinesCordon structure.
type MachinesCordonReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesCordonReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesCordonOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines/{machine_id}/cordon] Machines_cordon", response, response.Code())
	}
}

// NewMachinesCordonOK creates a MachinesCordonOK with default headers values
func NewMachinesCordonOK() *MachinesCordonOK {
	return &MachinesCordonOK{}
}

/*
MachinesCordonOK describes a response with status code 200, with default header values.

OK
*/
type MachinesCordonOK struct {
}

// IsSuccess returns true when this machines cordon o k response has a 2xx status code
func (o *MachinesCordonOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines cordon o k response has a 3xx status code
func (o *MachinesCordonOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines cordon o k response has a 4xx status code
func (o *MachinesCordonOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines cordon o k response has a 5xx status code
func (o *MachinesCordonOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines cordon o k response a status code equal to that given
func (o *MachinesCordonOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines cordon o k response
func (o *MachinesCordonOK) Code() int {
	return 200
}

func (o *MachinesCordonOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/cordon][%d] machinesCordonOK ", 200)
}

func (o *MachinesCordonOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/cordon][%d] machinesCordonOK ", 200)
}

func (o *MachinesCordonOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
