// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// MachinesSignalReader is a Reader for the MachinesSignal structure.
type MachinesSignalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachinesSignalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachinesSignalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMachinesSignalBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app_name}/machines/{machine_id}/signal] Machines_signal", response, response.Code())
	}
}

// NewMachinesSignalOK creates a MachinesSignalOK with default headers values
func NewMachinesSignalOK() *MachinesSignalOK {
	return &MachinesSignalOK{}
}

/*
MachinesSignalOK describes a response with status code 200, with default header values.

OK
*/
type MachinesSignalOK struct {
}

// IsSuccess returns true when this machines signal o k response has a 2xx status code
func (o *MachinesSignalOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this machines signal o k response has a 3xx status code
func (o *MachinesSignalOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines signal o k response has a 4xx status code
func (o *MachinesSignalOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this machines signal o k response has a 5xx status code
func (o *MachinesSignalOK) IsServerError() bool {
	return false
}

// IsCode returns true when this machines signal o k response a status code equal to that given
func (o *MachinesSignalOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the machines signal o k response
func (o *MachinesSignalOK) Code() int {
	return 200
}

func (o *MachinesSignalOK) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/signal][%d] machinesSignalOK ", 200)
}

func (o *MachinesSignalOK) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/signal][%d] machinesSignalOK ", 200)
}

func (o *MachinesSignalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMachinesSignalBadRequest creates a MachinesSignalBadRequest with default headers values
func NewMachinesSignalBadRequest() *MachinesSignalBadRequest {
	return &MachinesSignalBadRequest{}
}

/*
MachinesSignalBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MachinesSignalBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this machines signal bad request response has a 2xx status code
func (o *MachinesSignalBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this machines signal bad request response has a 3xx status code
func (o *MachinesSignalBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this machines signal bad request response has a 4xx status code
func (o *MachinesSignalBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this machines signal bad request response has a 5xx status code
func (o *MachinesSignalBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this machines signal bad request response a status code equal to that given
func (o *MachinesSignalBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the machines signal bad request response
func (o *MachinesSignalBadRequest) Code() int {
	return 400
}

func (o *MachinesSignalBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/signal][%d] machinesSignalBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesSignalBadRequest) String() string {
	return fmt.Sprintf("[POST /apps/{app_name}/machines/{machine_id}/signal][%d] machinesSignalBadRequest  %+v", 400, o.Payload)
}

func (o *MachinesSignalBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *MachinesSignalBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
