// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMachinesStartParams creates a new MachinesStartParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachinesStartParams() *MachinesStartParams {
	return &MachinesStartParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachinesStartParamsWithTimeout creates a new MachinesStartParams object
// with the ability to set a timeout on a request.
func NewMachinesStartParamsWithTimeout(timeout time.Duration) *MachinesStartParams {
	return &MachinesStartParams{
		timeout: timeout,
	}
}

// NewMachinesStartParamsWithContext creates a new MachinesStartParams object
// with the ability to set a context for a request.
func NewMachinesStartParamsWithContext(ctx context.Context) *MachinesStartParams {
	return &MachinesStartParams{
		Context: ctx,
	}
}

// NewMachinesStartParamsWithHTTPClient creates a new MachinesStartParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachinesStartParamsWithHTTPClient(client *http.Client) *MachinesStartParams {
	return &MachinesStartParams{
		HTTPClient: client,
	}
}

/*
MachinesStartParams contains all the parameters to send to the API endpoint

	for the machines start operation.

	Typically these are written to a http.Request.
*/
type MachinesStartParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	/* MachineID.

	   Machine ID
	*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machines start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesStartParams) WithDefaults() *MachinesStartParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machines start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachinesStartParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machines start params
func (o *MachinesStartParams) WithTimeout(timeout time.Duration) *MachinesStartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machines start params
func (o *MachinesStartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machines start params
func (o *MachinesStartParams) WithContext(ctx context.Context) *MachinesStartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machines start params
func (o *MachinesStartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machines start params
func (o *MachinesStartParams) WithHTTPClient(client *http.Client) *MachinesStartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machines start params
func (o *MachinesStartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the machines start params
func (o *MachinesStartParams) WithAppName(appName string) *MachinesStartParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the machines start params
func (o *MachinesStartParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithMachineID adds the machineID to the machines start params
func (o *MachinesStartParams) WithMachineID(machineID string) *MachinesStartParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the machines start params
func (o *MachinesStartParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *MachinesStartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	// path param machine_id
	if err := r.SetPathParam("machine_id", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
