// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// NewAppsCreateParams creates a new AppsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAppsCreateParams() *AppsCreateParams {
	return &AppsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAppsCreateParamsWithTimeout creates a new AppsCreateParams object
// with the ability to set a timeout on a request.
func NewAppsCreateParamsWithTimeout(timeout time.Duration) *AppsCreateParams {
	return &AppsCreateParams{
		timeout: timeout,
	}
}

// NewAppsCreateParamsWithContext creates a new AppsCreateParams object
// with the ability to set a context for a request.
func NewAppsCreateParamsWithContext(ctx context.Context) *AppsCreateParams {
	return &AppsCreateParams{
		Context: ctx,
	}
}

// NewAppsCreateParamsWithHTTPClient creates a new AppsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewAppsCreateParamsWithHTTPClient(client *http.Client) *AppsCreateParams {
	return &AppsCreateParams{
		HTTPClient: client,
	}
}

/*
AppsCreateParams contains all the parameters to send to the API endpoint

	for the apps create operation.

	Typically these are written to a http.Request.
*/
type AppsCreateParams struct {

	/* Request.

	   App body
	*/
	Request *models.CreateAppRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the apps create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppsCreateParams) WithDefaults() *AppsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the apps create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the apps create params
func (o *AppsCreateParams) WithTimeout(timeout time.Duration) *AppsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apps create params
func (o *AppsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apps create params
func (o *AppsCreateParams) WithContext(ctx context.Context) *AppsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apps create params
func (o *AppsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apps create params
func (o *AppsCreateParams) WithHTTPClient(client *http.Client) *AppsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apps create params
func (o *AppsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the apps create params
func (o *AppsCreateParams) WithRequest(request *models.CreateAppRequest) *AppsCreateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the apps create params
func (o *AppsCreateParams) SetRequest(request *models.CreateAppRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *AppsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
