// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAppsDeleteParams creates a new AppsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAppsDeleteParams() *AppsDeleteParams {
	return &AppsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAppsDeleteParamsWithTimeout creates a new AppsDeleteParams object
// with the ability to set a timeout on a request.
func NewAppsDeleteParamsWithTimeout(timeout time.Duration) *AppsDeleteParams {
	return &AppsDeleteParams{
		timeout: timeout,
	}
}

// NewAppsDeleteParamsWithContext creates a new AppsDeleteParams object
// with the ability to set a context for a request.
func NewAppsDeleteParamsWithContext(ctx context.Context) *AppsDeleteParams {
	return &AppsDeleteParams{
		Context: ctx,
	}
}

// NewAppsDeleteParamsWithHTTPClient creates a new AppsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAppsDeleteParamsWithHTTPClient(client *http.Client) *AppsDeleteParams {
	return &AppsDeleteParams{
		HTTPClient: client,
	}
}

/*
AppsDeleteParams contains all the parameters to send to the API endpoint

	for the apps delete operation.

	Typically these are written to a http.Request.
*/
type AppsDeleteParams struct {

	/* AppName.

	   Fly App Name
	*/
	AppName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the apps delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppsDeleteParams) WithDefaults() *AppsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the apps delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the apps delete params
func (o *AppsDeleteParams) WithTimeout(timeout time.Duration) *AppsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apps delete params
func (o *AppsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apps delete params
func (o *AppsDeleteParams) WithContext(ctx context.Context) *AppsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apps delete params
func (o *AppsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apps delete params
func (o *AppsDeleteParams) WithHTTPClient(client *http.Client) *AppsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apps delete params
func (o *AppsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the apps delete params
func (o *AppsDeleteParams) WithAppName(appName string) *AppsDeleteParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the apps delete params
func (o *AppsDeleteParams) SetAppName(appName string) {
	o.AppName = appName
}

// WriteToRequest writes these params to a swagger request
func (o *AppsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_name
	if err := r.SetPathParam("app_name", o.AppName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
