// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AppsDeleteReader is a Reader for the AppsDelete structure.
type AppsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewAppsDeleteAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /apps/{app_name}] Apps_delete", response, response.Code())
	}
}

// NewAppsDeleteAccepted creates a AppsDeleteAccepted with default headers values
func NewAppsDeleteAccepted() *AppsDeleteAccepted {
	return &AppsDeleteAccepted{}
}

/*
AppsDeleteAccepted describes a response with status code 202, with default header values.

Accepted
*/
type AppsDeleteAccepted struct {
}

// IsSuccess returns true when this apps delete accepted response has a 2xx status code
func (o *AppsDeleteAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this apps delete accepted response has a 3xx status code
func (o *AppsDeleteAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps delete accepted response has a 4xx status code
func (o *AppsDeleteAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this apps delete accepted response has a 5xx status code
func (o *AppsDeleteAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this apps delete accepted response a status code equal to that given
func (o *AppsDeleteAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the apps delete accepted response
func (o *AppsDeleteAccepted) Code() int {
	return 202
}

func (o *AppsDeleteAccepted) Error() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}][%d] appsDeleteAccepted ", 202)
}

func (o *AppsDeleteAccepted) String() string {
	return fmt.Sprintf("[DELETE /apps/{app_name}][%d] appsDeleteAccepted ", 202)
}

func (o *AppsDeleteAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
