// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattgonewild/fly/models"
)

// AppsCreateReader is a Reader for the AppsCreate structure.
type AppsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAppsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAppsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /apps] Apps_create", response, response.Code())
	}
}

// NewAppsCreateCreated creates a AppsCreateCreated with default headers values
func NewAppsCreateCreated() *AppsCreateCreated {
	return &AppsCreateCreated{}
}

/*
AppsCreateCreated describes a response with status code 201, with default header values.

Created
*/
type AppsCreateCreated struct {
}

// IsSuccess returns true when this apps create created response has a 2xx status code
func (o *AppsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this apps create created response has a 3xx status code
func (o *AppsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps create created response has a 4xx status code
func (o *AppsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this apps create created response has a 5xx status code
func (o *AppsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this apps create created response a status code equal to that given
func (o *AppsCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the apps create created response
func (o *AppsCreateCreated) Code() int {
	return 201
}

func (o *AppsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /apps][%d] appsCreateCreated ", 201)
}

func (o *AppsCreateCreated) String() string {
	return fmt.Sprintf("[POST /apps][%d] appsCreateCreated ", 201)
}

func (o *AppsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAppsCreateBadRequest creates a AppsCreateBadRequest with default headers values
func NewAppsCreateBadRequest() *AppsCreateBadRequest {
	return &AppsCreateBadRequest{}
}

/*
AppsCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type AppsCreateBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this apps create bad request response has a 2xx status code
func (o *AppsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this apps create bad request response has a 3xx status code
func (o *AppsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps create bad request response has a 4xx status code
func (o *AppsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this apps create bad request response has a 5xx status code
func (o *AppsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this apps create bad request response a status code equal to that given
func (o *AppsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the apps create bad request response
func (o *AppsCreateBadRequest) Code() int {
	return 400
}

func (o *AppsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps][%d] appsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *AppsCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /apps][%d] appsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *AppsCreateBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AppsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
