// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIHTTPResponseOptions api HTTP response options
//
// swagger:model api.HTTPResponseOptions
type APIHTTPResponseOptions struct {

	// headers
	Headers interface{} `json:"headers,omitempty"`
}

// Validate validates this api HTTP response options
func (m *APIHTTPResponseOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api HTTP response options based on context it is used
func (m *APIHTTPResponseOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIHTTPResponseOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIHTTPResponseOptions) UnmarshalBinary(b []byte) error {
	var res APIHTTPResponseOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
