// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMachineHTTPHeader For http checks, an array of objects with string field Name and array of strings field Values. The key/value pairs specify header and header values that will get passed with the check call.
//
// swagger:model api.MachineHTTPHeader
type APIMachineHTTPHeader struct {

	// The header name
	Name string `json:"name,omitempty"`

	// The header value
	Values []string `json:"values"`
}

// Validate validates this api machine HTTP header
func (m *APIMachineHTTPHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api machine HTTP header based on context it is used
func (m *APIMachineHTTPHeader) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMachineHTTPHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMachineHTTPHeader) UnmarshalBinary(b []byte) error {
	var res APIMachineHTTPHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
