// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIStopConfig api stop config
//
// swagger:model api.StopConfig
type APIStopConfig struct {

	// signal
	Signal string `json:"signal,omitempty"`

	// timeout
	Timeout string `json:"timeout,omitempty"`
}

// Validate validates this api stop config
func (m *APIStopConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api stop config based on context it is used
func (m *APIStopConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIStopConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIStopConfig) UnmarshalBinary(b []byte) error {
	var res APIStopConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
