// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMachineGuest api machine guest
//
// swagger:model api.MachineGuest
type APIMachineGuest struct {

	// cpu kind
	CPUKind string `json:"cpu_kind,omitempty"`

	// cpus
	Cpus int64 `json:"cpus,omitempty"`

	// gpu kind
	GpuKind string `json:"gpu_kind,omitempty"`

	// host dedication id
	HostDedicationID string `json:"host_dedication_id,omitempty"`

	// kernel args
	KernelArgs []string `json:"kernel_args"`

	// memory mb
	MemoryMb int64 `json:"memory_mb,omitempty"`
}

// Validate validates this api machine guest
func (m *APIMachineGuest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api machine guest based on context it is used
func (m *APIMachineGuest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMachineGuest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMachineGuest) UnmarshalBinary(b []byte) error {
	var res APIMachineGuest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
