// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMachineMount api machine mount
//
// swagger:model api.MachineMount
type APIMachineMount struct {

	// add size gb
	AddSizeGb int64 `json:"add_size_gb,omitempty"`

	// encrypted
	Encrypted bool `json:"encrypted,omitempty"`

	// extend threshold percent
	ExtendThresholdPercent int64 `json:"extend_threshold_percent,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// size gb
	SizeGb int64 `json:"size_gb,omitempty"`

	// size gb limit
	SizeGbLimit int64 `json:"size_gb_limit,omitempty"`

	// volume
	Volume string `json:"volume,omitempty"`
}

// Validate validates this api machine mount
func (m *APIMachineMount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api machine mount based on context it is used
func (m *APIMachineMount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMachineMount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMachineMount) UnmarshalBinary(b []byte) error {
	var res APIMachineMount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
