// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMachineServiceConcurrency api machine service concurrency
//
// swagger:model api.MachineServiceConcurrency
type APIMachineServiceConcurrency struct {

	// hard limit
	HardLimit int64 `json:"hard_limit,omitempty"`

	// soft limit
	SoftLimit int64 `json:"soft_limit,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this api machine service concurrency
func (m *APIMachineServiceConcurrency) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api machine service concurrency based on context it is used
func (m *APIMachineServiceConcurrency) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMachineServiceConcurrency) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMachineServiceConcurrency) UnmarshalBinary(b []byte) error {
	var res APIMachineServiceConcurrency
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
