// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMachineMetrics api machine metrics
//
// swagger:model api.MachineMetrics
type APIMachineMetrics struct {

	// path
	Path string `json:"path,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`
}

// Validate validates this api machine metrics
func (m *APIMachineMetrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api machine metrics based on context it is used
func (m *APIMachineMetrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMachineMetrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMachineMetrics) UnmarshalBinary(b []byte) error {
	var res APIMachineMetrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
