// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMachineProcess api machine process
//
// swagger:model api.MachineProcess
type APIMachineProcess struct {

	// cmd
	Cmd []string `json:"cmd"`

	// entrypoint
	Entrypoint []string `json:"entrypoint"`

	// env
	Env map[string]string `json:"env,omitempty"`

	// exec
	Exec []string `json:"exec"`

	// user
	User string `json:"user,omitempty"`
}

// Validate validates this api machine process
func (m *APIMachineProcess) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api machine process based on context it is used
func (m *APIMachineProcess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMachineProcess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMachineProcess) UnmarshalBinary(b []byte) error {
	var res APIMachineProcess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
