// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIDNSConfig api DNS config
//
// swagger:model api.DNSConfig
type APIDNSConfig struct {

	// skip registration
	SkipRegistration bool `json:"skip_registration,omitempty"`
}

// Validate validates this api DNS config
func (m *APIDNSConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api DNS config based on context it is used
func (m *APIDNSConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIDNSConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIDNSConfig) UnmarshalBinary(b []byte) error {
	var res APIDNSConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
