// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIProxyProtoOptions api proxy proto options
//
// swagger:model api.ProxyProtoOptions
type APIProxyProtoOptions struct {

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this api proxy proto options
func (m *APIProxyProtoOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api proxy proto options based on context it is used
func (m *APIProxyProtoOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIProxyProtoOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIProxyProtoOptions) UnmarshalBinary(b []byte) error {
	var res APIProxyProtoOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
