// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIStatic api static
//
// swagger:model api.Static
type APIStatic struct {

	// guest path
	// Required: true
	GuestPath *string `json:"guest_path"`

	// url prefix
	// Required: true
	URLPrefix *string `json:"url_prefix"`
}

// Validate validates this api static
func (m *APIStatic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGuestPath(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURLPrefix(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIStatic) validateGuestPath(formats strfmt.Registry) error {

	if err := validate.Required("guest_path", "body", m.GuestPath); err != nil {
		return err
	}

	return nil
}

func (m *APIStatic) validateURLPrefix(formats strfmt.Registry) error {

	if err := validate.Required("url_prefix", "body", m.URLPrefix); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api static based on context it is used
func (m *APIStatic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIStatic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIStatic) UnmarshalBinary(b []byte) error {
	var res APIStatic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
