// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APITLSOptions api TLS options
//
// swagger:model api.TLSOptions
type APITLSOptions struct {

	// alpn
	Alpn []string `json:"alpn"`

	// default self signed
	DefaultSelfSigned bool `json:"default_self_signed,omitempty"`

	// versions
	Versions []string `json:"versions"`
}

// Validate validates this api TLS options
func (m *APITLSOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api TLS options based on context it is used
func (m *APITLSOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APITLSOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APITLSOptions) UnmarshalBinary(b []byte) error {
	var res APITLSOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
