// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateAppRequest create app request
//
// swagger:model CreateAppRequest
type CreateAppRequest struct {

	// app name
	AppName string `json:"app_name,omitempty"`

	// app role id
	AppRoleID string `json:"app_role_id,omitempty"`

	// network
	Network string `json:"network,omitempty"`

	// org slug
	OrgSlug string `json:"org_slug,omitempty"`
}

// Validate validates this create app request
func (m *CreateAppRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create app request based on context it is used
func (m *CreateAppRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateAppRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAppRequest) UnmarshalBinary(b []byte) error {
	var res CreateAppRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
