// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExtendVolumeRequest extend volume request
//
// swagger:model ExtendVolumeRequest
type ExtendVolumeRequest struct {

	// size gb
	SizeGb int64 `json:"size_gb,omitempty"`
}

// Validate validates this extend volume request
func (m *ExtendVolumeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this extend volume request based on context it is used
func (m *ExtendVolumeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExtendVolumeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtendVolumeRequest) UnmarshalBinary(b []byte) error {
	var res ExtendVolumeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
