// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImageRef image ref
//
// swagger:model ImageRef
type ImageRef struct {

	// digest
	Digest string `json:"digest,omitempty"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// registry
	Registry string `json:"registry,omitempty"`

	// repository
	Repository string `json:"repository,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`
}

// Validate validates this image ref
func (m *ImageRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image ref based on context it is used
func (m *ImageRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageRef) UnmarshalBinary(b []byte) error {
	var res ImageRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
