// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListApp list app
//
// swagger:model ListApp
type ListApp struct {

	// id
	ID string `json:"id,omitempty"`

	// machine count
	MachineCount int64 `json:"machine_count,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// network
	Network interface{} `json:"network,omitempty"`
}

// Validate validates this list app
func (m *ListApp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list app based on context it is used
func (m *ListApp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListApp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListApp) UnmarshalBinary(b []byte) error {
	var res ListApp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
