// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListenSocket listen socket
//
// swagger:model ListenSocket
type ListenSocket struct {

	// address
	Address string `json:"address,omitempty"`

	// proto
	Proto string `json:"proto,omitempty"`
}

// Validate validates this listen socket
func (m *ListenSocket) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this listen socket based on context it is used
func (m *ListenSocket) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListenSocket) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListenSocket) UnmarshalBinary(b []byte) error {
	var res ListenSocket
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
