// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MachineEvent machine event
//
// swagger:model MachineEvent
type MachineEvent struct {

	// id
	ID string `json:"id,omitempty"`

	// request
	Request interface{} `json:"request,omitempty"`

	// source
	Source string `json:"source,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this machine event
func (m *MachineEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this machine event based on context it is used
func (m *MachineEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MachineEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MachineEvent) UnmarshalBinary(b []byte) error {
	var res MachineEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
