// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MachineExecRequest machine exec request
//
// swagger:model MachineExecRequest
type MachineExecRequest struct {

	// Deprecated: use Command instead
	Cmd string `json:"cmd,omitempty"`

	// command
	Command []string `json:"command"`

	// timeout
	Timeout int64 `json:"timeout,omitempty"`
}

// Validate validates this machine exec request
func (m *MachineExecRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this machine exec request based on context it is used
func (m *MachineExecRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MachineExecRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MachineExecRequest) UnmarshalBinary(b []byte) error {
	var res MachineExecRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
