// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MachineVersion machine version
//
// swagger:model MachineVersion
type MachineVersion struct {

	// user config
	UserConfig *APIMachineConfig `json:"user_config,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this machine version
func (m *MachineVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MachineVersion) validateUserConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.UserConfig) { // not required
		return nil
	}

	if m.UserConfig != nil {
		if err := m.UserConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("user_config")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this machine version based on the context it is used
func (m *MachineVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUserConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MachineVersion) contextValidateUserConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.UserConfig != nil {

		if swag.IsZero(m.UserConfig) { // not required
			return nil
		}

		if err := m.UserConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("user_config")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MachineVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MachineVersion) UnmarshalBinary(b []byte) error {
	var res MachineVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
