// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StopRequest stop request
//
// swagger:model StopRequest
type StopRequest struct {

	// signal
	Signal string `json:"signal,omitempty"`

	// timeout
	Timeout string `json:"timeout,omitempty"`
}

// Validate validates this stop request
func (m *StopRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stop request based on context it is used
func (m *StopRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StopRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StopRequest) UnmarshalBinary(b []byte) error {
	var res StopRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
