// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateMachineRequest update machine request
//
// swagger:model UpdateMachineRequest
type UpdateMachineRequest struct {

	// An object defining the Machine configuration
	Config struct {
		APIMachineConfig
	} `json:"config,omitempty"`

	// current version
	CurrentVersion string `json:"current_version,omitempty"`

	// lease ttl
	LeaseTTL int64 `json:"lease_ttl,omitempty"`

	// lsvd
	Lsvd bool `json:"lsvd,omitempty"`

	// Unique name for this Machine. If omitted, one is generated for you
	Name string `json:"name,omitempty"`

	// The target region. Omitting this param launches in the same region as your WireGuard peer connection (somewhere near you).
	Region string `json:"region,omitempty"`

	// skip launch
	SkipLaunch bool `json:"skip_launch,omitempty"`

	// skip service registration
	SkipServiceRegistration bool `json:"skip_service_registration,omitempty"`
}

// Validate validates this update machine request
func (m *UpdateMachineRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateMachineRequest) validateConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.Config) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this update machine request based on the context it is used
func (m *UpdateMachineRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateMachineRequest) contextValidateConfig(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateMachineRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateMachineRequest) UnmarshalBinary(b []byte) error {
	var res UpdateMachineRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
