// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateVolumeRequest update volume request
//
// swagger:model UpdateVolumeRequest
type UpdateVolumeRequest struct {

	// snapshot retention
	SnapshotRetention int64 `json:"snapshot_retention,omitempty"`
}

// Validate validates this update volume request
func (m *UpdateVolumeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update volume request based on context it is used
func (m *UpdateVolumeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateVolumeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateVolumeRequest) UnmarshalBinary(b []byte) error {
	var res UpdateVolumeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
