// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Volume volume
//
// swagger:model Volume
type Volume struct {

	// attached alloc id
	AttachedAllocID string `json:"attached_alloc_id,omitempty"`

	// attached machine id
	AttachedMachineID string `json:"attached_machine_id,omitempty"`

	// block size
	BlockSize int64 `json:"block_size,omitempty"`

	// blocks
	Blocks int64 `json:"blocks,omitempty"`

	// blocks avail
	BlocksAvail int64 `json:"blocks_avail,omitempty"`

	// blocks free
	BlocksFree int64 `json:"blocks_free,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// encrypted
	Encrypted bool `json:"encrypted,omitempty"`

	// fstype
	Fstype string `json:"fstype,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// size gb
	SizeGb int64 `json:"size_gb,omitempty"`

	// snapshot retention
	SnapshotRetention int64 `json:"snapshot_retention,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// zone
	Zone string `json:"zone,omitempty"`
}

// Validate validates this volume
func (m *Volume) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this volume based on context it is used
func (m *Volume) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Volume) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Volume) UnmarshalBinary(b []byte) error {
	var res Volume
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
